# Generated by Django 3.1.5 on 2021-02-07 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210129_1731'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='follow',
            name='period',
        ),
        migrations.AddField(
            model_name='profile',
            name='period',
            field=models.DurationField(default=datetime.timedelta(seconds=43200)),
        ),
    ]
